/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TelemedicineRouteImport } from './routes/telemedicine'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecondOpinionRouteImport } from './routes/second-opinion'
import { Route as RateRouteImport } from './routes/rate'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as InternationalPatientsRouteImport } from './routes/international-patients'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as HomeCareRouteImport } from './routes/home-care'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExcellenceRouteImport } from './routes/excellence'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplexRouteImport } from './routes/complex'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccreditationsRouteImport } from './routes/accreditations'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as HealthIndexRouteImport } from './routes/health.index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'
import { Route as SettingsGithubRouteImport } from './routes/settings.github'
import { Route as MediaStoriesRouteImport } from './routes/media.stories'
import { Route as MediaNewsRouteImport } from './routes/media.news'
import { Route as HealthSearchRouteImport } from './routes/health.search'
import { Route as HealthSlugRouteImport } from './routes/health.$slug'
import { Route as ExcellenceSlugRouteImport } from './routes/excellence.$slug'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as BranchesSlugRouteImport } from './routes/branches.$slug'
import { Route as AccreditationsIdRouteImport } from './routes/accreditations.$id'
import { Route as AuthenticatedTransitionsStatsRouteImport } from './routes/_authenticated/transitions-stats'
import { Route as AuthenticatedTransitionAlertsRouteImport } from './routes/_authenticated/transition-alerts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecondOpinionAdminRouteImport } from './routes/_authenticated/second-opinion-admin'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRbacRouteImport } from './routes/_authenticated/rbac'
import { Route as AuthenticatedRatingsRouteImport } from './routes/_authenticated/ratings'
import { Route as AuthenticatedQuickAddRouteImport } from './routes/_authenticated/quick-add'
import { Route as AuthenticatedQrCardsRouteImport } from './routes/_authenticated/qr-cards'
import { Route as AuthenticatedPatientsManagementRouteImport } from './routes/_authenticated/patients-management'
import { Route as AuthenticatedPatientsAnalyticsRouteImport } from './routes/_authenticated/patients-analytics'
import { Route as AuthenticatedPatientStoriesAdminRouteImport } from './routes/_authenticated/patient-stories-admin'
import { Route as AuthenticatedNotificationsQueueRouteImport } from './routes/_authenticated/notifications-queue'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedMessageTemplatesRouteImport } from './routes/_authenticated/message-templates'
import { Route as AuthenticatedMcpStatusRouteImport } from './routes/_authenticated/mcp-status'
import { Route as AuthenticatedDoctorsManagementRouteImport } from './routes/_authenticated/doctors-management'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorporateAdminRouteImport } from './routes/_authenticated/corporate-admin'
import { Route as AuthenticatedClinicSettingsRouteImport } from './routes/_authenticated/clinic-settings'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAuditExportRouteImport } from './routes/_authenticated/audit-export'
import { Route as AuthenticatedAppointmentsQueueRouteImport } from './routes/_authenticated/appointments-queue'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as MediaStoriesSlugRouteImport } from './routes/media.stories.$slug'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicBookTrackRouteImport } from './routes/api/public/book/track'
import { Route as ApiPublicBookMonthAvailabilityRouteImport } from './routes/api/public/book/month-availability'
import { Route as ApiPublicBookCreateRouteImport } from './routes/api/public/book/create'
import { Route as ApiPublicBookAvailabilityRouteImport } from './routes/api/public/book/availability'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineRoute = TelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondOpinionRoute = SecondOpinionRouteImport.update({
  id: '/second-opinion',
  path: '/second-opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalPatientsRoute = InternationalPatientsRouteImport.update({
  id: '/international-patients',
  path: '/international-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCareRoute = HomeCareRouteImport.update({
  id: '/home-care',
  path: '/home-care',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcellenceRoute = ExcellenceRouteImport.update({
  id: '/excellence',
  path: '/excellence',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexRoute = ComplexRouteImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccreditationsRoute = AccreditationsRouteImport.update({
  id: '/accreditations',
  path: '/accreditations',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/specialties/',
  path: '/specialties/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGithubRoute = SettingsGithubRouteImport.update({
  id: '/settings/github',
  path: '/settings/github',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaStoriesRoute = MediaStoriesRouteImport.update({
  id: '/media/stories',
  path: '/media/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaNewsRoute = MediaNewsRouteImport.update({
  id: '/media/news',
  path: '/media/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSearchRoute = HealthSearchRouteImport.update({
  id: '/health/search',
  path: '/health/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSlugRoute = HealthSlugRouteImport.update({
  id: '/health/$slug',
  path: '/health/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcellenceSlugRoute = ExcellenceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExcellenceRoute,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesSlugRoute = BranchesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BranchesRoute,
} as any)
const AccreditationsIdRoute = AccreditationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccreditationsRoute,
} as any)
const AuthenticatedTransitionsStatsRoute =
  AuthenticatedTransitionsStatsRouteImport.update({
    id: '/transitions-stats',
    path: '/transitions-stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransitionAlertsRoute =
  AuthenticatedTransitionAlertsRouteImport.update({
    id: '/transition-alerts',
    path: '/transition-alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecondOpinionAdminRoute =
  AuthenticatedSecondOpinionAdminRouteImport.update({
    id: '/second-opinion-admin',
    path: '/second-opinion-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRbacRoute = AuthenticatedRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRatingsRoute = AuthenticatedRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickAddRoute = AuthenticatedQuickAddRouteImport.update({
  id: '/quick-add',
  path: '/quick-add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrCardsRoute = AuthenticatedQrCardsRouteImport.update({
  id: '/qr-cards',
  path: '/qr-cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsManagementRoute =
  AuthenticatedPatientsManagementRouteImport.update({
    id: '/patients-management',
    path: '/patients-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsAnalyticsRoute =
  AuthenticatedPatientsAnalyticsRouteImport.update({
    id: '/patients-analytics',
    path: '/patients-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientStoriesAdminRoute =
  AuthenticatedPatientStoriesAdminRouteImport.update({
    id: '/patient-stories-admin',
    path: '/patient-stories-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsQueueRoute =
  AuthenticatedNotificationsQueueRouteImport.update({
    id: '/notifications-queue',
    path: '/notifications-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessageTemplatesRoute =
  AuthenticatedMessageTemplatesRouteImport.update({
    id: '/message-templates',
    path: '/message-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMcpStatusRoute = AuthenticatedMcpStatusRouteImport.update({
  id: '/mcp-status',
  path: '/mcp-status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorsManagementRoute =
  AuthenticatedDoctorsManagementRouteImport.update({
    id: '/doctors-management',
    path: '/doctors-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorporateAdminRoute =
  AuthenticatedCorporateAdminRouteImport.update({
    id: '/corporate-admin',
    path: '/corporate-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClinicSettingsRoute =
  AuthenticatedClinicSettingsRouteImport.update({
    id: '/clinic-settings',
    path: '/clinic-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditExportRoute =
  AuthenticatedAuditExportRouteImport.update({
    id: '/audit-export',
    path: '/audit-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsQueueRoute =
  AuthenticatedAppointmentsQueueRouteImport.update({
    id: '/appointments-queue',
    path: '/appointments-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MediaStoriesSlugRoute = MediaStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MediaStoriesRoute,
} as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookTrackRoute = ApiPublicBookTrackRouteImport.update({
  id: '/api/public/book/track',
  path: '/api/public/book/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookMonthAvailabilityRoute =
  ApiPublicBookMonthAvailabilityRouteImport.update({
    id: '/api/public/book/month-availability',
    path: '/api/public/book/month-availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookCreateRoute = ApiPublicBookCreateRouteImport.update({
  id: '/api/public/book/create',
  path: '/api/public/book/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookAvailabilityRoute =
  ApiPublicBookAvailabilityRouteImport.update({
    id: '/api/public/book/availability',
    path: '/api/public/book/availability',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accreditations': typeof AccreditationsRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/branches': typeof BranchesRouteWithChildren
  '/careers': typeof CareersRoute
  '/complaints': typeof ComplaintsRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/emergency': typeof EmergencyRoute
  '/excellence': typeof ExcellenceRouteWithChildren
  '/faq': typeof FaqRoute
  '/home-care': typeof HomeCareRoute
  '/insurance': typeof InsuranceRoute
  '/international-patients': typeof InternationalPatientsRoute
  '/lookup': typeof LookupRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/pharmacy': typeof PharmacyRoute
  '/programs': typeof ProgramsRoute
  '/rate': typeof RateRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telemedicine': typeof TelemedicineRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointments-queue': typeof AuthenticatedAppointmentsQueueRoute
  '/audit-export': typeof AuthenticatedAuditExportRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clinic-settings': typeof AuthenticatedClinicSettingsRoute
  '/corporate-admin': typeof AuthenticatedCorporateAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors-management': typeof AuthenticatedDoctorsManagementRoute
  '/mcp-status': typeof AuthenticatedMcpStatusRoute
  '/message-templates': typeof AuthenticatedMessageTemplatesRoute
  '/my': typeof AuthenticatedMyRoute
  '/notifications-queue': typeof AuthenticatedNotificationsQueueRoute
  '/patient-stories-admin': typeof AuthenticatedPatientStoriesAdminRoute
  '/patients-analytics': typeof AuthenticatedPatientsAnalyticsRoute
  '/patients-management': typeof AuthenticatedPatientsManagementRoute
  '/qr-cards': typeof AuthenticatedQrCardsRoute
  '/quick-add': typeof AuthenticatedQuickAddRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/second-opinion-admin': typeof AuthenticatedSecondOpinionAdminRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transition-alerts': typeof AuthenticatedTransitionAlertsRoute
  '/transitions-stats': typeof AuthenticatedTransitionsStatsRoute
  '/accreditations/$id': typeof AccreditationsIdRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/excellence/$slug': typeof ExcellenceSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/health/search': typeof HealthSearchRoute
  '/media/news': typeof MediaNewsRoute
  '/media/stories': typeof MediaStoriesRouteWithChildren
  '/settings/github': typeof SettingsGithubRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/media/stories/$slug': typeof MediaStoriesSlugRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/book/availability': typeof ApiPublicBookAvailabilityRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
  '/api/public/book/month-availability': typeof ApiPublicBookMonthAvailabilityRoute
  '/api/public/book/track': typeof ApiPublicBookTrackRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accreditations': typeof AccreditationsRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/branches': typeof BranchesRouteWithChildren
  '/careers': typeof CareersRoute
  '/complaints': typeof ComplaintsRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/emergency': typeof EmergencyRoute
  '/excellence': typeof ExcellenceRouteWithChildren
  '/faq': typeof FaqRoute
  '/home-care': typeof HomeCareRoute
  '/insurance': typeof InsuranceRoute
  '/international-patients': typeof InternationalPatientsRoute
  '/lookup': typeof LookupRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/pharmacy': typeof PharmacyRoute
  '/programs': typeof ProgramsRoute
  '/rate': typeof RateRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telemedicine': typeof TelemedicineRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/appointments-queue': typeof AuthenticatedAppointmentsQueueRoute
  '/audit-export': typeof AuthenticatedAuditExportRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clinic-settings': typeof AuthenticatedClinicSettingsRoute
  '/corporate-admin': typeof AuthenticatedCorporateAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors-management': typeof AuthenticatedDoctorsManagementRoute
  '/mcp-status': typeof AuthenticatedMcpStatusRoute
  '/message-templates': typeof AuthenticatedMessageTemplatesRoute
  '/my': typeof AuthenticatedMyRoute
  '/notifications-queue': typeof AuthenticatedNotificationsQueueRoute
  '/patient-stories-admin': typeof AuthenticatedPatientStoriesAdminRoute
  '/patients-analytics': typeof AuthenticatedPatientsAnalyticsRoute
  '/patients-management': typeof AuthenticatedPatientsManagementRoute
  '/qr-cards': typeof AuthenticatedQrCardsRoute
  '/quick-add': typeof AuthenticatedQuickAddRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/second-opinion-admin': typeof AuthenticatedSecondOpinionAdminRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transition-alerts': typeof AuthenticatedTransitionAlertsRoute
  '/transitions-stats': typeof AuthenticatedTransitionsStatsRoute
  '/accreditations/$id': typeof AccreditationsIdRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/excellence/$slug': typeof ExcellenceSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/health/search': typeof HealthSearchRoute
  '/media/news': typeof MediaNewsRoute
  '/media/stories': typeof MediaStoriesRouteWithChildren
  '/settings/github': typeof SettingsGithubRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors': typeof DoctorsIndexRoute
  '/health': typeof HealthIndexRoute
  '/specialties': typeof SpecialtiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/media/stories/$slug': typeof MediaStoriesSlugRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/api/public/book/availability': typeof ApiPublicBookAvailabilityRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
  '/api/public/book/month-availability': typeof ApiPublicBookMonthAvailabilityRoute
  '/api/public/book/track': typeof ApiPublicBookTrackRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accreditations': typeof AccreditationsRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/branches': typeof BranchesRouteWithChildren
  '/careers': typeof CareersRoute
  '/complaints': typeof ComplaintsRoute
  '/complex': typeof ComplexRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/emergency': typeof EmergencyRoute
  '/excellence': typeof ExcellenceRouteWithChildren
  '/faq': typeof FaqRoute
  '/home-care': typeof HomeCareRoute
  '/insurance': typeof InsuranceRoute
  '/international-patients': typeof InternationalPatientsRoute
  '/lookup': typeof LookupRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/pharmacy': typeof PharmacyRoute
  '/programs': typeof ProgramsRoute
  '/rate': typeof RateRoute
  '/second-opinion': typeof SecondOpinionRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telemedicine': typeof TelemedicineRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/appointments-queue': typeof AuthenticatedAppointmentsQueueRoute
  '/_authenticated/audit-export': typeof AuthenticatedAuditExportRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clinic-settings': typeof AuthenticatedClinicSettingsRoute
  '/_authenticated/corporate-admin': typeof AuthenticatedCorporateAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctors-management': typeof AuthenticatedDoctorsManagementRoute
  '/_authenticated/mcp-status': typeof AuthenticatedMcpStatusRoute
  '/_authenticated/message-templates': typeof AuthenticatedMessageTemplatesRoute
  '/_authenticated/my': typeof AuthenticatedMyRoute
  '/_authenticated/notifications-queue': typeof AuthenticatedNotificationsQueueRoute
  '/_authenticated/patient-stories-admin': typeof AuthenticatedPatientStoriesAdminRoute
  '/_authenticated/patients-analytics': typeof AuthenticatedPatientsAnalyticsRoute
  '/_authenticated/patients-management': typeof AuthenticatedPatientsManagementRoute
  '/_authenticated/qr-cards': typeof AuthenticatedQrCardsRoute
  '/_authenticated/quick-add': typeof AuthenticatedQuickAddRoute
  '/_authenticated/ratings': typeof AuthenticatedRatingsRoute
  '/_authenticated/rbac': typeof AuthenticatedRbacRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/second-opinion-admin': typeof AuthenticatedSecondOpinionAdminRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transition-alerts': typeof AuthenticatedTransitionAlertsRoute
  '/_authenticated/transitions-stats': typeof AuthenticatedTransitionsStatsRoute
  '/accreditations/$id': typeof AccreditationsIdRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/excellence/$slug': typeof ExcellenceSlugRoute
  '/health/$slug': typeof HealthSlugRoute
  '/health/search': typeof HealthSearchRoute
  '/media/news': typeof MediaNewsRoute
  '/media/stories': typeof MediaStoriesRouteWithChildren
  '/settings/github': typeof SettingsGithubRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health/': typeof HealthIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/media/stories/$slug': typeof MediaStoriesSlugRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/book/availability': typeof ApiPublicBookAvailabilityRoute
  '/api/public/book/create': typeof ApiPublicBookCreateRoute
  '/api/public/book/month-availability': typeof ApiPublicBookMonthAvailabilityRoute
  '/api/public/book/track': typeof ApiPublicBookTrackRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accreditations'
    | '/app'
    | '/auth'
    | '/book'
    | '/booking-confirmation'
    | '/branches'
    | '/careers'
    | '/complaints'
    | '/complex'
    | '/contact'
    | '/corporate'
    | '/emergency'
    | '/excellence'
    | '/faq'
    | '/home-care'
    | '/insurance'
    | '/international-patients'
    | '/lookup'
    | '/mcp'
    | '/packages'
    | '/pharmacy'
    | '/programs'
    | '/rate'
    | '/second-opinion'
    | '/services'
    | '/sitemap.xml'
    | '/telemedicine'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/appointments-queue'
    | '/audit-export'
    | '/audit-log'
    | '/calendar'
    | '/clinic-settings'
    | '/corporate-admin'
    | '/dashboard'
    | '/doctors-management'
    | '/mcp-status'
    | '/message-templates'
    | '/my'
    | '/notifications-queue'
    | '/patient-stories-admin'
    | '/patients-analytics'
    | '/patients-management'
    | '/qr-cards'
    | '/quick-add'
    | '/ratings'
    | '/rbac'
    | '/reports'
    | '/second-opinion-admin'
    | '/settings'
    | '/transition-alerts'
    | '/transitions-stats'
    | '/accreditations/$id'
    | '/branches/$slug'
    | '/doctors/$slug'
    | '/excellence/$slug'
    | '/health/$slug'
    | '/health/search'
    | '/media/news'
    | '/media/stories'
    | '/settings/github'
    | '/specialties/$slug'
    | '/doctors/'
    | '/health/'
    | '/specialties/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/patients/$patientId'
    | '/media/stories/$slug'
    | '/patients/'
    | '/api/public/book/availability'
    | '/api/public/book/create'
    | '/api/public/book/month-availability'
    | '/api/public/book/track'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accreditations'
    | '/app'
    | '/auth'
    | '/book'
    | '/booking-confirmation'
    | '/branches'
    | '/careers'
    | '/complaints'
    | '/complex'
    | '/contact'
    | '/corporate'
    | '/emergency'
    | '/excellence'
    | '/faq'
    | '/home-care'
    | '/insurance'
    | '/international-patients'
    | '/lookup'
    | '/mcp'
    | '/packages'
    | '/pharmacy'
    | '/programs'
    | '/rate'
    | '/second-opinion'
    | '/services'
    | '/sitemap.xml'
    | '/telemedicine'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/appointments-queue'
    | '/audit-export'
    | '/audit-log'
    | '/calendar'
    | '/clinic-settings'
    | '/corporate-admin'
    | '/dashboard'
    | '/doctors-management'
    | '/mcp-status'
    | '/message-templates'
    | '/my'
    | '/notifications-queue'
    | '/patient-stories-admin'
    | '/patients-analytics'
    | '/patients-management'
    | '/qr-cards'
    | '/quick-add'
    | '/ratings'
    | '/rbac'
    | '/reports'
    | '/second-opinion-admin'
    | '/settings'
    | '/transition-alerts'
    | '/transitions-stats'
    | '/accreditations/$id'
    | '/branches/$slug'
    | '/doctors/$slug'
    | '/excellence/$slug'
    | '/health/$slug'
    | '/health/search'
    | '/media/news'
    | '/media/stories'
    | '/settings/github'
    | '/specialties/$slug'
    | '/doctors'
    | '/health'
    | '/specialties'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/patients/$patientId'
    | '/media/stories/$slug'
    | '/patients'
    | '/api/public/book/availability'
    | '/api/public/book/create'
    | '/api/public/book/month-availability'
    | '/api/public/book/track'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accreditations'
    | '/app'
    | '/auth'
    | '/book'
    | '/booking-confirmation'
    | '/branches'
    | '/careers'
    | '/complaints'
    | '/complex'
    | '/contact'
    | '/corporate'
    | '/emergency'
    | '/excellence'
    | '/faq'
    | '/home-care'
    | '/insurance'
    | '/international-patients'
    | '/lookup'
    | '/mcp'
    | '/packages'
    | '/pharmacy'
    | '/programs'
    | '/rate'
    | '/second-opinion'
    | '/services'
    | '/sitemap.xml'
    | '/telemedicine'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/appointments-queue'
    | '/_authenticated/audit-export'
    | '/_authenticated/audit-log'
    | '/_authenticated/calendar'
    | '/_authenticated/clinic-settings'
    | '/_authenticated/corporate-admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctors-management'
    | '/_authenticated/mcp-status'
    | '/_authenticated/message-templates'
    | '/_authenticated/my'
    | '/_authenticated/notifications-queue'
    | '/_authenticated/patient-stories-admin'
    | '/_authenticated/patients-analytics'
    | '/_authenticated/patients-management'
    | '/_authenticated/qr-cards'
    | '/_authenticated/quick-add'
    | '/_authenticated/ratings'
    | '/_authenticated/rbac'
    | '/_authenticated/reports'
    | '/_authenticated/second-opinion-admin'
    | '/_authenticated/settings'
    | '/_authenticated/transition-alerts'
    | '/_authenticated/transitions-stats'
    | '/accreditations/$id'
    | '/branches/$slug'
    | '/doctors/$slug'
    | '/excellence/$slug'
    | '/health/$slug'
    | '/health/search'
    | '/media/news'
    | '/media/stories'
    | '/settings/github'
    | '/specialties/$slug'
    | '/doctors/'
    | '/health/'
    | '/specialties/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/patients/$patientId'
    | '/media/stories/$slug'
    | '/_authenticated/patients/'
    | '/api/public/book/availability'
    | '/api/public/book/create'
    | '/api/public/book/month-availability'
    | '/api/public/book/track'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccreditationsRoute: typeof AccreditationsRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  BranchesRoute: typeof BranchesRouteWithChildren
  CareersRoute: typeof CareersRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ComplexRoute: typeof ComplexRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  EmergencyRoute: typeof EmergencyRoute
  ExcellenceRoute: typeof ExcellenceRouteWithChildren
  FaqRoute: typeof FaqRoute
  HomeCareRoute: typeof HomeCareRoute
  InsuranceRoute: typeof InsuranceRoute
  InternationalPatientsRoute: typeof InternationalPatientsRoute
  LookupRoute: typeof LookupRoute
  McpRoute: typeof McpRoute
  PackagesRoute: typeof PackagesRoute
  PharmacyRoute: typeof PharmacyRoute
  ProgramsRoute: typeof ProgramsRoute
  RateRoute: typeof RateRoute
  SecondOpinionRoute: typeof SecondOpinionRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TelemedicineRoute: typeof TelemedicineRoute
  TrackRoute: typeof TrackRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  HealthSlugRoute: typeof HealthSlugRoute
  HealthSearchRoute: typeof HealthSearchRoute
  MediaNewsRoute: typeof MediaNewsRoute
  MediaStoriesRoute: typeof MediaStoriesRouteWithChildren
  SettingsGithubRoute: typeof SettingsGithubRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBookAvailabilityRoute: typeof ApiPublicBookAvailabilityRoute
  ApiPublicBookCreateRoute: typeof ApiPublicBookCreateRoute
  ApiPublicBookMonthAvailabilityRoute: typeof ApiPublicBookMonthAvailabilityRoute
  ApiPublicBookTrackRoute: typeof ApiPublicBookTrackRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine': {
      id: '/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof TelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-opinion': {
      id: '/second-opinion'
      path: '/second-opinion'
      fullPath: '/second-opinion'
      preLoaderRoute: typeof SecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-patients': {
      id: '/international-patients'
      path: '/international-patients'
      fullPath: '/international-patients'
      preLoaderRoute: typeof InternationalPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-care': {
      id: '/home-care'
      path: '/home-care'
      fullPath: '/home-care'
      preLoaderRoute: typeof HomeCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excellence': {
      id: '/excellence'
      path: '/excellence'
      fullPath: '/excellence'
      preLoaderRoute: typeof ExcellenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complex': {
      id: '/complex'
      path: '/complex'
      fullPath: '/complex'
      preLoaderRoute: typeof ComplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accreditations': {
      id: '/accreditations'
      path: '/accreditations'
      fullPath: '/accreditations'
      preLoaderRoute: typeof AccreditationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/specialties'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/github': {
      id: '/settings/github'
      path: '/settings/github'
      fullPath: '/settings/github'
      preLoaderRoute: typeof SettingsGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/stories': {
      id: '/media/stories'
      path: '/media/stories'
      fullPath: '/media/stories'
      preLoaderRoute: typeof MediaStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/news': {
      id: '/media/news'
      path: '/media/news'
      fullPath: '/media/news'
      preLoaderRoute: typeof MediaNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/search': {
      id: '/health/search'
      path: '/health/search'
      fullPath: '/health/search'
      preLoaderRoute: typeof HealthSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$slug': {
      id: '/health/$slug'
      path: '/health/$slug'
      fullPath: '/health/$slug'
      preLoaderRoute: typeof HealthSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excellence/$slug': {
      id: '/excellence/$slug'
      path: '/$slug'
      fullPath: '/excellence/$slug'
      preLoaderRoute: typeof ExcellenceSlugRouteImport
      parentRoute: typeof ExcellenceRoute
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$slug': {
      id: '/branches/$slug'
      path: '/$slug'
      fullPath: '/branches/$slug'
      preLoaderRoute: typeof BranchesSlugRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/accreditations/$id': {
      id: '/accreditations/$id'
      path: '/$id'
      fullPath: '/accreditations/$id'
      preLoaderRoute: typeof AccreditationsIdRouteImport
      parentRoute: typeof AccreditationsRoute
    }
    '/_authenticated/transitions-stats': {
      id: '/_authenticated/transitions-stats'
      path: '/transitions-stats'
      fullPath: '/transitions-stats'
      preLoaderRoute: typeof AuthenticatedTransitionsStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transition-alerts': {
      id: '/_authenticated/transition-alerts'
      path: '/transition-alerts'
      fullPath: '/transition-alerts'
      preLoaderRoute: typeof AuthenticatedTransitionAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/second-opinion-admin': {
      id: '/_authenticated/second-opinion-admin'
      path: '/second-opinion-admin'
      fullPath: '/second-opinion-admin'
      preLoaderRoute: typeof AuthenticatedSecondOpinionAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rbac': {
      id: '/_authenticated/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AuthenticatedRbacRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ratings': {
      id: '/_authenticated/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof AuthenticatedRatingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-add': {
      id: '/_authenticated/quick-add'
      path: '/quick-add'
      fullPath: '/quick-add'
      preLoaderRoute: typeof AuthenticatedQuickAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-cards': {
      id: '/_authenticated/qr-cards'
      path: '/qr-cards'
      fullPath: '/qr-cards'
      preLoaderRoute: typeof AuthenticatedQrCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients-management': {
      id: '/_authenticated/patients-management'
      path: '/patients-management'
      fullPath: '/patients-management'
      preLoaderRoute: typeof AuthenticatedPatientsManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients-analytics': {
      id: '/_authenticated/patients-analytics'
      path: '/patients-analytics'
      fullPath: '/patients-analytics'
      preLoaderRoute: typeof AuthenticatedPatientsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-stories-admin': {
      id: '/_authenticated/patient-stories-admin'
      path: '/patient-stories-admin'
      fullPath: '/patient-stories-admin'
      preLoaderRoute: typeof AuthenticatedPatientStoriesAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications-queue': {
      id: '/_authenticated/notifications-queue'
      path: '/notifications-queue'
      fullPath: '/notifications-queue'
      preLoaderRoute: typeof AuthenticatedNotificationsQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/message-templates': {
      id: '/_authenticated/message-templates'
      path: '/message-templates'
      fullPath: '/message-templates'
      preLoaderRoute: typeof AuthenticatedMessageTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp-status': {
      id: '/_authenticated/mcp-status'
      path: '/mcp-status'
      fullPath: '/mcp-status'
      preLoaderRoute: typeof AuthenticatedMcpStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors-management': {
      id: '/_authenticated/doctors-management'
      path: '/doctors-management'
      fullPath: '/doctors-management'
      preLoaderRoute: typeof AuthenticatedDoctorsManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corporate-admin': {
      id: '/_authenticated/corporate-admin'
      path: '/corporate-admin'
      fullPath: '/corporate-admin'
      preLoaderRoute: typeof AuthenticatedCorporateAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinic-settings': {
      id: '/_authenticated/clinic-settings'
      path: '/clinic-settings'
      fullPath: '/clinic-settings'
      preLoaderRoute: typeof AuthenticatedClinicSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-export': {
      id: '/_authenticated/audit-export'
      path: '/audit-export'
      fullPath: '/audit-export'
      preLoaderRoute: typeof AuthenticatedAuditExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments-queue': {
      id: '/_authenticated/appointments-queue'
      path: '/appointments-queue'
      fullPath: '/appointments-queue'
      preLoaderRoute: typeof AuthenticatedAppointmentsQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/media/stories/$slug': {
      id: '/media/stories/$slug'
      path: '/$slug'
      fullPath: '/media/stories/$slug'
      preLoaderRoute: typeof MediaStoriesSlugRouteImport
      parentRoute: typeof MediaStoriesRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book/track': {
      id: '/api/public/book/track'
      path: '/api/public/book/track'
      fullPath: '/api/public/book/track'
      preLoaderRoute: typeof ApiPublicBookTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book/month-availability': {
      id: '/api/public/book/month-availability'
      path: '/api/public/book/month-availability'
      fullPath: '/api/public/book/month-availability'
      preLoaderRoute: typeof ApiPublicBookMonthAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book/create': {
      id: '/api/public/book/create'
      path: '/api/public/book/create'
      fullPath: '/api/public/book/create'
      preLoaderRoute: typeof ApiPublicBookCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book/availability': {
      id: '/api/public/book/availability'
      path: '/api/public/book/availability'
      fullPath: '/api/public/book/availability'
      preLoaderRoute: typeof ApiPublicBookAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppointmentsQueueRoute: typeof AuthenticatedAppointmentsQueueRoute
  AuthenticatedAuditExportRoute: typeof AuthenticatedAuditExportRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClinicSettingsRoute: typeof AuthenticatedClinicSettingsRoute
  AuthenticatedCorporateAdminRoute: typeof AuthenticatedCorporateAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorsManagementRoute: typeof AuthenticatedDoctorsManagementRoute
  AuthenticatedMcpStatusRoute: typeof AuthenticatedMcpStatusRoute
  AuthenticatedMessageTemplatesRoute: typeof AuthenticatedMessageTemplatesRoute
  AuthenticatedMyRoute: typeof AuthenticatedMyRoute
  AuthenticatedNotificationsQueueRoute: typeof AuthenticatedNotificationsQueueRoute
  AuthenticatedPatientStoriesAdminRoute: typeof AuthenticatedPatientStoriesAdminRoute
  AuthenticatedPatientsAnalyticsRoute: typeof AuthenticatedPatientsAnalyticsRoute
  AuthenticatedPatientsManagementRoute: typeof AuthenticatedPatientsManagementRoute
  AuthenticatedQrCardsRoute: typeof AuthenticatedQrCardsRoute
  AuthenticatedQuickAddRoute: typeof AuthenticatedQuickAddRoute
  AuthenticatedRatingsRoute: typeof AuthenticatedRatingsRoute
  AuthenticatedRbacRoute: typeof AuthenticatedRbacRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecondOpinionAdminRoute: typeof AuthenticatedSecondOpinionAdminRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransitionAlertsRoute: typeof AuthenticatedTransitionAlertsRoute
  AuthenticatedTransitionsStatsRoute: typeof AuthenticatedTransitionsStatsRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppointmentsQueueRoute: AuthenticatedAppointmentsQueueRoute,
  AuthenticatedAuditExportRoute: AuthenticatedAuditExportRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClinicSettingsRoute: AuthenticatedClinicSettingsRoute,
  AuthenticatedCorporateAdminRoute: AuthenticatedCorporateAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorsManagementRoute: AuthenticatedDoctorsManagementRoute,
  AuthenticatedMcpStatusRoute: AuthenticatedMcpStatusRoute,
  AuthenticatedMessageTemplatesRoute: AuthenticatedMessageTemplatesRoute,
  AuthenticatedMyRoute: AuthenticatedMyRoute,
  AuthenticatedNotificationsQueueRoute: AuthenticatedNotificationsQueueRoute,
  AuthenticatedPatientStoriesAdminRoute: AuthenticatedPatientStoriesAdminRoute,
  AuthenticatedPatientsAnalyticsRoute: AuthenticatedPatientsAnalyticsRoute,
  AuthenticatedPatientsManagementRoute: AuthenticatedPatientsManagementRoute,
  AuthenticatedQrCardsRoute: AuthenticatedQrCardsRoute,
  AuthenticatedQuickAddRoute: AuthenticatedQuickAddRoute,
  AuthenticatedRatingsRoute: AuthenticatedRatingsRoute,
  AuthenticatedRbacRoute: AuthenticatedRbacRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecondOpinionAdminRoute: AuthenticatedSecondOpinionAdminRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransitionAlertsRoute: AuthenticatedTransitionAlertsRoute,
  AuthenticatedTransitionsStatsRoute: AuthenticatedTransitionsStatsRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AccreditationsRouteChildren {
  AccreditationsIdRoute: typeof AccreditationsIdRoute
}

const AccreditationsRouteChildren: AccreditationsRouteChildren = {
  AccreditationsIdRoute: AccreditationsIdRoute,
}

const AccreditationsRouteWithChildren = AccreditationsRoute._addFileChildren(
  AccreditationsRouteChildren,
)

interface BranchesRouteChildren {
  BranchesSlugRoute: typeof BranchesSlugRoute
}

const BranchesRouteChildren: BranchesRouteChildren = {
  BranchesSlugRoute: BranchesSlugRoute,
}

const BranchesRouteWithChildren = BranchesRoute._addFileChildren(
  BranchesRouteChildren,
)

interface ExcellenceRouteChildren {
  ExcellenceSlugRoute: typeof ExcellenceSlugRoute
}

const ExcellenceRouteChildren: ExcellenceRouteChildren = {
  ExcellenceSlugRoute: ExcellenceSlugRoute,
}

const ExcellenceRouteWithChildren = ExcellenceRoute._addFileChildren(
  ExcellenceRouteChildren,
)

interface MediaStoriesRouteChildren {
  MediaStoriesSlugRoute: typeof MediaStoriesSlugRoute
}

const MediaStoriesRouteChildren: MediaStoriesRouteChildren = {
  MediaStoriesSlugRoute: MediaStoriesSlugRoute,
}

const MediaStoriesRouteWithChildren = MediaStoriesRoute._addFileChildren(
  MediaStoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccreditationsRoute: AccreditationsRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  BranchesRoute: BranchesRouteWithChildren,
  CareersRoute: CareersRoute,
  ComplaintsRoute: ComplaintsRoute,
  ComplexRoute: ComplexRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  EmergencyRoute: EmergencyRoute,
  ExcellenceRoute: ExcellenceRouteWithChildren,
  FaqRoute: FaqRoute,
  HomeCareRoute: HomeCareRoute,
  InsuranceRoute: InsuranceRoute,
  InternationalPatientsRoute: InternationalPatientsRoute,
  LookupRoute: LookupRoute,
  McpRoute: McpRoute,
  PackagesRoute: PackagesRoute,
  PharmacyRoute: PharmacyRoute,
  ProgramsRoute: ProgramsRoute,
  RateRoute: RateRoute,
  SecondOpinionRoute: SecondOpinionRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TelemedicineRoute: TelemedicineRoute,
  TrackRoute: TrackRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  HealthSlugRoute: HealthSlugRoute,
  HealthSearchRoute: HealthSearchRoute,
  MediaNewsRoute: MediaNewsRoute,
  MediaStoriesRoute: MediaStoriesRouteWithChildren,
  SettingsGithubRoute: SettingsGithubRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBookAvailabilityRoute: ApiPublicBookAvailabilityRoute,
  ApiPublicBookCreateRoute: ApiPublicBookCreateRoute,
  ApiPublicBookMonthAvailabilityRoute: ApiPublicBookMonthAvailabilityRoute,
  ApiPublicBookTrackRoute: ApiPublicBookTrackRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
